version: '3.8'

services:
    ##################################################
    #                                                #
    #     _  ________ _____  _   _ ______ _          #
    #    | |/ /  ____|  __ \| \ | |  ____| |         #
    #    | ' /| |__  | |__) |  \| | |__  | |         #
    #    |  < |  __| |  _  /| . ` |  __| | |         #
    #    | . \| |____| | \ \| |\  | |____| |____     #
    #    |_|\_\______|_|  \_\_| \_|______|______|    #
    #                                                #
    ##################################################
    kernel: 
        image: kodmain/kernel
        profiles:
            - kernel
        build:
            context: src/kernel
            platforms:
                - "linux/arm64"
                - "linux/amd64"
  
    ##################################################################
    #                                                                #
    #      _____ ______ _______      _______ _____ ______  _____     #
    #     / ____|  ____|  __ \ \    / /_   _/ ____|  ____|/ ____|    #
    #    | (___ | |__  | |__) \ \  / /  | || |    | |__  | (___      #
    #     \___ \|  __| |  _  / \ \/ /   | || |    |  __|  \___ \     #
    #     ____) | |____| | \ \  \  /   _| || |____| |____ ____) |    #
    #    |_____/|______|_|  \_\  \/   |_____\_____|______|_____/     #
    #                                                                #
    ##################################################################