FROM ubuntu:latest as base

LABEL maintainer="MakingCodes <contact@making.codes>"
LABEL description="Generic Ubuntu image"

# UPDATE
RUN apt-get update && apt-get upgrade -y &&\
    apt-get install -y nano git openssh-client zsh make wget doas bash

# ZSH
RUN echo "ZDOTDIR=/etc/zsh" >> /etc/zsh/zshenv
RUN wget -qO - https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | zsh
COPY --chown=root:root /etc /etc

RUN usermod -s /bin/zsh -d /home/nobody nobody &&\
    usermod -s /bin/zsh root

USER nobody
WORKDIR /home/nobody

ENTRYPOINT [ "/bin/zsh" ]
