FROM alpine:edge as base

LABEL maintainer="MakingCodes <contact@making.codes>"
LABEL description="Generic alpine image"

# UPDATE
RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/main"       > /etc/apk/repositories &&\
	echo "https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories &&\
	echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing"   >> /etc/apk/repositories &&\
	apk update && apk upgrade --no-cache
RUN apk add --no-cache nano
RUN apk add --no-cache git
RUN apk add --no-cache openssh
RUN apk add --no-cache rclone
RUN apk add --no-cache zsh
RUN apk add --no-cache make
RUN apk add --no-cache shadow
RUN apk add --no-cache doas
RUN apk add --no-cache bash
RUN apk add --no-cache htop
RUN apk add --no-cache curl
RUN apk add --no-cache wget
RUN apk add --no-cache jq

# ZSH
RUN echo "ZDOTDIR=/etc/zsh" >> /etc/zsh/zshenv
RUN wget -qO - https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | zsh
COPY --chown=root:root /etc /etc

RUN usermod -s /bin/zsh -d /home/nobody nobody &&\
	usermod -s /bin/zsh root

RUN ARCHITECTURE=$(uname -m) && if [ "$ARCHITECTURE" = "aarch64" ] || [ "$ARCHITECTURE" = "arm64" ]; then \
      echo "export ARCHITECTURE=arm64" >> /etc/profile; \
    else \
      echo "export ARCHITECTURE=amd64" >> /etc/profile; \
    fi;

USER nobody:nobody
WORKDIR /home/nobody

ENTRYPOINT [ "/bin/zsh" ]