FROM kodmain/core:alpine as kernel
USER root:root
RUN apk add --no-cache \
	alpine-sdk \
	go \
	php composer \
	nodejs npm \
	rust rustup cargo \
	python3 python3-dev \
	ruby ruby-dev \
	$(apk search openjdk | grep "^openjdk[0-9]" | sort -t 'k' -k 2 -n -u| awk -F '-' '{print $1}' | tail -n1) \
	upx
USER nobody:nobody