FROM kodmain/os:alpine as kernel
USER root:root
RUN apk add --no-cache \
	ruby ruby-dev build-base openssl-dev yaml-dev libffi-dev readline-dev zlib-dev && \
	gem update --system && gem update 
USER nobody:nobody