name: DockerImage

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:

  os:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          os_name:
            - alpine
            - ubuntu
    outputs:
      OS_SIGN: ${{ steps.sign.outputs.changed }}
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Dockerfile Change
      id: sign
      run: make change ${{ matrix.os_name }}
    - name: Login to Docker Hub
      if: ${{ github.event_name != 'push' || steps.sign.outputs.changed == 'true' }}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GitHub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      if: ${{ github.event_name != 'push' || steps.sign.outputs.changed == 'true' }}
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      if: ${{ github.event_name != 'push' || steps.sign.outputs.changed == 'true' }}
      uses: docker/setup-buildx-action@v3
    - name: Build Image
      if: ${{ github.event_name != 'push' || steps.sign.outputs.changed == 'true' }}
      uses: docker/build-push-action@v5
      with:
        file: src/os/${{ matrix.os_name }}/dockerfile
        context: src/os/${{ matrix.os_name }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{secrets.DOCKERHUB_USERNAME}}/os:${{ matrix.os_name }}
          ghcr.io/${{ github.repository_owner }}/os:${{ matrix.os_name }}
    - name: Docker Scout
      id: docker-scout
      uses: docker/scout-action@main
      with:
        dockerhub-user: ${{secrets.DOCKERHUB_USERNAME}}
        dockerhub-password: ${{secrets.DOCKERHUB_TOKEN}}
        command: cves
        image: ${{secrets.DOCKERHUB_USERNAME}}/os:${{ matrix.os_name }}
        to-latest: true
        ignore-base: true
        ignore-unchanged: true
        only-fixed: true
        

  builder:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          builder_name:
            - all
            - c
            - go
            - java
            - nodejs
            - php
            - python
            - ruby
            - rust
            - perl
    outputs:
      BUILDER_SIGN: ${{ steps.sign.outputs.changed }}
    needs: os
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Dockerfile Change
      id: sign
      run: make change ${{ matrix.builder_name }}
      env:
        OS_SIGN: ${{ needs.os.outputs.OS_SIGN }}
    - name: Login to Docker Hub
      if: ${{ github.event_name != 'push' || steps.sign.outputs.changed == 'true' }}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GitHub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up QEMU
      if: ${{ github.event_name != 'push' || steps.sign.outputs.changed == 'true' }}
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      if: ${{ github.event_name != 'push' || steps.sign.outputs.changed == 'true' }}
      uses: docker/setup-buildx-action@v3
    - name: Build Image
      if: ${{ github.event_name != 'push' || steps.sign.outputs.changed == 'true' }}
      uses: docker/build-push-action@v5
      with:
        file: src/builder/${{ matrix.builder_name }}/dockerfile
        context: src/builder/${{ matrix.builder_name }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{secrets.DOCKERHUB_USERNAME}}/builder:${{ matrix.builder_name }}
          ghcr.io/${{ github.repository_owner }}/builder:${{ matrix.builder_name }}
    - name: Docker Scout
      id: docker-scout
      uses: docker/scout-action@main
      with:
        dockerhub-user: ${{secrets.DOCKERHUB_USERNAME}}
        dockerhub-password: ${{secrets.DOCKERHUB_TOKEN}}
        command: cves
        image: ${{secrets.DOCKERHUB_USERNAME}}/builder:${{ matrix.builder_name }}
        to-latest: true
        ignore-base: true
        ignore-unchanged: true
        only-fixed: true

  service:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          service_name:
            - wireguard
    outputs:
      SERVICE_SIGN: ${{ steps.sign.outputs.changed }}
    needs: builder
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Dockerfile Change
      id: sign
      run: make change ${{ matrix.service_name }}
      env:
        BUILDER_SIGN: ${{ needs.builder.outputs.BUILDER_SIGN }}
    - name: Login to Docker Hub
      if: ${{ github.event_name != 'push' || steps.sign.outputs.changed == 'true' }}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      if: ${{ github.event_name != 'push' || steps.sign.outputs.changed == 'true' }}
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      if: ${{ github.event_name != 'push' || steps.sign.outputs.changed == 'true' }}
      uses: docker/setup-buildx-action@v3
    - name: Build Image
      if: ${{ github.event_name != 'push' || steps.sign.outputs.changed == 'true' }}
      uses: docker/build-push-action@v5
      with:
        file: src/service/${{ matrix.service_name }}/dockerfile
        context: src/service/${{ matrix.service_name }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{secrets.DOCKERHUB_USERNAME}}/service:${{ matrix.service_name }}
          ghcr.io/${{ github.repository_owner }}/service:${{ matrix.service_name }}
    - name: Docker Scout
      id: docker-scout
      uses: docker/scout-action@main
      with:
        dockerhub-user: ${{secrets.DOCKERHUB_USERNAME}}
        dockerhub-password: ${{secrets.DOCKERHUB_TOKEN}}
        command: cves
        image: ${{secrets.DOCKERHUB_USERNAME}}/service:${{ matrix.service_name }}
        to-latest: true
        ignore-base: true
        ignore-unchanged: true
        only-fixed: true
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}