name: Build images

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:

  core:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build alpine
      uses: docker/build-push-action@v4
      with:
        file: src/core/alpine/dockerfile
        context: src/core/alpine
        platforms: linux/amd64,linux/arm64
        push: true
        tags: kodmain/core:alpine

    - name: Build ubuntu
      uses: docker/build-push-action@v4
      with:
        file: src/core/ubuntu/dockerfile
        context: src/core/ubuntu
        platforms: linux/amd64,linux/arm64
        push: true
        tags: kodmain/core:ubuntu

  service:
    runs-on: ubuntu-latest
    needs: core
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build naked
      uses: docker/build-push-action@v4
      with:
        file: src/service/naked/dockerfile
        context: src/service/naked
        platforms: linux/amd64,linux/arm64
        push: true
        tags: kodmain/service:naked

    - name: Build review
      uses: docker/build-push-action@v4
      with:
        file: src/service/review/dockerfile
        context: src/service/review
        platforms: linux/amd64,linux/arm64
        push: true
        tags: kodmain/service:review