name: Build images

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:

  core:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          core_name:
            - alpine
            - ubuntu
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build Image
      uses: docker/build-push-action@v4
      with:
        file: src/core/${{ matrix.core_name }}/dockerfile
        context: src/core/${{ matrix.core_name }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          kodmain/core:${{ matrix.core_name }}
          kodmain/core:${{ matrix.core_name }}

  service:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          service_name:
            - review
            - root
    needs: core
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Image
      uses: docker/build-push-action@v4
      with:
        file: src/service/${{ matrix.service_name }}/dockerfile
        context: src/service/${{ matrix.service_name }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          kodmain/service:${{ matrix.service_name }}
          kodmain/service:${{ matrix.service_name }}