name: service/naked

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - name: Check for Dockerfile changes
      id: dockerfile_changes
      uses: "pullreminders/changeset-action@v1"
      with:
        path: "src/core/naked/dockerfile"
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push kernel
      uses: docker/build-push-action@v4
      if: ${{ steps.dockerfile_changes.outputs.changed == 'true' }}
      with:
        file: src/service/naked/dockerfile
        context: src/service/naked
        platforms: linux/amd64,linux/arm64
        push: true
        tags: kodmain/service:naked